import Head from 'next/head'
import React, { useState, useEffect } from "react";
import axios from "axios";
import Link from 'next/link';

export default function Home() {
  const [users, setUser] = useState([]);
 
  useEffect(() => {
    getUsers();
  }, []);
 
  const getUsers = async () => {
    const response = await axios.get("http://localhost:5000/users");
    setUser(response.data);
  };
 
  const deleteUser = async (id) => {
    try {
      await axios.delete(`http://localhost:5000/users/${id}`);
      getUsers();
    } catch (error) {
      console.log(error);
    }
  };
 
  return (
    <div className="bg-gray-500 h-[100vh]">

      <Head>
        <title>Contact App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" flex justify-center">

        <div className="w-1/2   mt-10">
        <button className='bg-green-600 text-white px-5 py-2 rounded-md '>
        <Link href='/AddUser' >Tambah Users</Link>
        </button>
            <table className="border-collapse bg-slate-700 border border-slate-500 w-full">
              <thead>
                <tr className='text-white'>
                  <th className='border border-slate-600 '>No</th>
                  <th className='border border-slate-600 '>Name</th>
                  <th className='border border-slate-600 '>Email</th>
                  <th className='border border-slate-600 '>Gender</th>
                  <th className='border border-slate-600 '>Actions</th>
                </tr>
              </thead>
              <tbody className='text-white text-center'>
                {users.map((user, index) => (
                  <tr key={user._id}>
                    <td className='border border-slate-600 '>{index + 1}</td>
                    <td className='border border-slate-600 '>{user.name}</td>
                    <td className='border border-slate-600 '>{user.email}</td>
                    <td className='border border-slate-600 '>{user.gender}</td>
                    <td className='border border-slate-600 '>
                      <button className="bg-blue-400 px-4 py-2 rounded-md mr-2 m-1">
                        <Link href={'/EditUser/'+user._id}>Edit User
                      </Link>
                    </button>
                    <button
                    onClick={() => deleteUser(user._id)}
                    className="bg-red-400 px-4 py-2 rounded-md "
                    >
                    Delete
                    </button>
                    </td>

                  </tr>
                ))}
              </tbody>
            </table>
          </div>
      </div>
    </div>
  )
}
